/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dataSetLength 
 * @param highestValue 
 * @param lowestValue 
 * @param `data` 
 */


data class AudioAttachmentModelWaveform (

    @Json(name = "dataSetLength")
    val dataSetLength: kotlin.Int,

    @Json(name = "highestValue")
    val highestValue: kotlin.Int,

    @Json(name = "lowestValue")
    val lowestValue: kotlin.Int,

    @Json(name = "data")
    val `data`: kotlin.collections.List<kotlin.Int>

) {


}

