/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.UserModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param needs2FA If true, the user has not yet been authenticated, and will need to submit the 2FA token to complete authentication.
 * @param user 
 */


data class AuthLoginV3Response (

    /* If true, the user has not yet been authenticated, and will need to submit the 2FA token to complete authentication. */
    @Json(name = "needs2FA")
    val needs2FA: kotlin.Boolean,

    @Json(name = "user")
    val user: UserModel? = null

) {


}

