/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.BlogPostModelV3Channel
import com.coulterpeterson.floatnative.openapi.models.BlogPostModelV3Creator
import com.coulterpeterson.floatnative.openapi.models.ImageModel
import com.coulterpeterson.floatnative.openapi.models.PostMetadataModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param guid 
 * @param title 
 * @param text Text description of the post. May have HTML paragraph (`<p>`) tags surrounding it, along with other HTML..
 * @param type 
 * @param channel 
 * @param tags 
 * @param attachmentOrder 
 * @param metadata 
 * @param releaseDate 
 * @param likes 
 * @param dislikes 
 * @param score 
 * @param comments 
 * @param creator 
 * @param wasReleasedSilently 
 * @param isAccessible If false, the post should be marked as locked and not viewable by the user.
 * @param thumbnail 
 * @param videoAttachments May be undefined, usually when `isAccessible` is `false`.
 * @param audioAttachments May be undefined, usually when `isAccessible` is `false`.
 * @param pictureAttachments May be undefined, usually when `isAccessible` is `false`.
 * @param galleryAttachments May be undefined, usually when `isAccessible` is `false`.
 */


data class BlogPostModelV3 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "guid")
    val guid: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    /* Text description of the post. May have HTML paragraph (`<p>`) tags surrounding it, along with other HTML.. */
    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "type")
    val type: BlogPostModelV3.Type,

    @Json(name = "channel")
    val channel: BlogPostModelV3Channel,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "attachmentOrder")
    val attachmentOrder: kotlin.collections.List<kotlin.String>,

    @Json(name = "metadata")
    val metadata: PostMetadataModel,

    @Json(name = "releaseDate")
    val releaseDate: java.time.OffsetDateTime,

    @Json(name = "likes")
    val likes: kotlin.Int,

    @Json(name = "dislikes")
    val dislikes: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "comments")
    val comments: kotlin.Int,

    @Json(name = "creator")
    val creator: BlogPostModelV3Creator,

    @Json(name = "wasReleasedSilently")
    val wasReleasedSilently: kotlin.Boolean,

    /* If false, the post should be marked as locked and not viewable by the user. */
    @Json(name = "isAccessible")
    val isAccessible: kotlin.Boolean,

    @Json(name = "thumbnail")
    val thumbnail: ImageModel? = null,

    /* May be undefined, usually when `isAccessible` is `false`. */
    @Json(name = "videoAttachments")
    val videoAttachments: kotlin.collections.List<kotlin.String>? = null,

    /* May be undefined, usually when `isAccessible` is `false`. */
    @Json(name = "audioAttachments")
    val audioAttachments: kotlin.collections.List<kotlin.String>? = null,

    /* May be undefined, usually when `isAccessible` is `false`. */
    @Json(name = "pictureAttachments")
    val pictureAttachments: kotlin.collections.List<kotlin.String>? = null,

    /* May be undefined, usually when `isAccessible` is `false`. */
    @Json(name = "galleryAttachments")
    val galleryAttachments: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: blogPost
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "blogPost") blogPost("blogPost");
    }

}

