/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.BlogPostModelV3CreatorOwner
import com.coulterpeterson.floatnative.openapi.models.CreatorModelV3Category
import com.coulterpeterson.floatnative.openapi.models.ImageModel
import com.coulterpeterson.floatnative.openapi.models.LiveStreamModel
import com.coulterpeterson.floatnative.openapi.models.SubscriptionPlanModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param owner 
 * @param title 
 * @param urlname Shown in the browser URL, and used in `/creator/named` queries.
 * @param description 
 * @param about 
 * @param category 
 * @param cover 
 * @param icon 
 * @param liveStream 
 * @param subscriptionPlans 
 * @param discoverable 
 * @param subscriberCountDisplay 
 * @param incomeDisplay 
 * @param defaultChannel 
 * @param channels 
 * @param card 
 */


data class BlogPostModelV3Creator (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "owner")
    val owner: BlogPostModelV3CreatorOwner,

    @Json(name = "title")
    val title: kotlin.String,

    /* Shown in the browser URL, and used in `/creator/named` queries. */
    @Json(name = "urlname")
    val urlname: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "about")
    val about: kotlin.String,

    @Json(name = "category")
    val category: CreatorModelV3Category,

    @Json(name = "cover")
    val cover: ImageModel?,

    @Json(name = "icon")
    val icon: ImageModel,

    @Json(name = "liveStream")
    val liveStream: LiveStreamModel?,

    @Json(name = "subscriptionPlans")
    val subscriptionPlans: kotlin.collections.List<SubscriptionPlanModel>,

    @Json(name = "discoverable")
    val discoverable: kotlin.Boolean,

    @Json(name = "subscriberCountDisplay")
    val subscriberCountDisplay: kotlin.String,

    @Json(name = "incomeDisplay")
    val incomeDisplay: kotlin.Boolean,

    @Json(name = "defaultChannel")
    val defaultChannel: kotlin.String? = null,

    @Json(name = "channels")
    val channels: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "card")
    val card: ImageModel? = null

) {


}

