/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV2ResourceModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cdn The domain of the CDN server to use. Combine with data from the `resource` object to create a full URL.
 * @param strategy Which download/streaming strategy to use. If `cdn`, then a `cdn` property will be included with the response. Otherwise, if set to `client`, then a `client` property will be included with the response. The cdn or client property should be combined with the `resource` property to perform the download/stream.
 * @param resource 
 */


data class CdnDeliveryV2VodLivestreamResponse (

    /* The domain of the CDN server to use. Combine with data from the `resource` object to create a full URL. */
    @Json(name = "cdn")
    val cdn: java.net.URI,

    /* Which download/streaming strategy to use. If `cdn`, then a `cdn` property will be included with the response. Otherwise, if set to `client`, then a `client` property will be included with the response. The cdn or client property should be combined with the `resource` property to perform the download/stream. */
    @Json(name = "strategy")
    val strategy: CdnDeliveryV2VodLivestreamResponse.Strategy,

    @Json(name = "resource")
    val resource: CdnDeliveryV2ResourceModel

) {

    /**
     * Which download/streaming strategy to use. If `cdn`, then a `cdn` property will be included with the response. Otherwise, if set to `client`, then a `client` property will be included with the response. The cdn or client property should be combined with the `resource` property to perform the download/stream.
     *
     * Values: cdn,client
     */
    @JsonClass(generateAdapter = false)
    enum class Strategy(val value: kotlin.String) {
        @Json(name = "cdn") cdn("cdn"),
        @Json(name = "client") client("client");
    }

}

