/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a quality of video to download/stream.
 *
 * @param name Used to identify this level of quality, and to refer to the `qualityLevelParams` object below by the property key.
 * @param label The display-friendly version of `name`.
 * @param order The display order to be shown to the user.
 * @param width The video quality's resolution's width in pixels.
 * @param height The video quality resolution's height in pixels.
 * @param mimeType 
 * @param codecs 
 */


data class CdnDeliveryV2QualityLevelModel (

    /* Used to identify this level of quality, and to refer to the `qualityLevelParams` object below by the property key. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The display-friendly version of `name`. */
    @Json(name = "label")
    val label: kotlin.String,

    /* The display order to be shown to the user. */
    @Json(name = "order")
    val order: kotlin.Int,

    /* The video quality's resolution's width in pixels. */
    @Json(name = "width")
    val width: kotlin.Int? = null,

    /* The video quality resolution's height in pixels. */
    @Json(name = "height")
    val height: kotlin.Int? = null,

    @Json(name = "mimeType")
    val mimeType: kotlin.String? = null,

    @Json(name = "codecs")
    val codecs: kotlin.String? = null

) {


}

