/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param codec RFC 6381 codec string indicating stream data chunk format.
 * @param codecSimple RFC 6381 codec string indicating stream format on the most basic level, without the addition of profile/level/etc. information.
 * @param mimeType MIME-type for individual stream data chunks (as opposed to a containing playlist).
 * @param width Count of horizontal pixels presented.
 * @param height Count of vertical pixels presented.
 * @param isHdr Whether or not this data stream carries HDR content.
 */


data class CdnDeliveryV3MetaImage (

    /* RFC 6381 codec string indicating stream data chunk format. */
    @Json(name = "codec")
    val codec: kotlin.String? = null,

    /* RFC 6381 codec string indicating stream format on the most basic level, without the addition of profile/level/etc. information. */
    @Json(name = "codecSimple")
    val codecSimple: kotlin.String? = null,

    /* MIME-type for individual stream data chunks (as opposed to a containing playlist). */
    @Json(name = "mimeType")
    val mimeType: kotlin.String? = null,

    /* Count of horizontal pixels presented. */
    @Json(name = "width")
    val width: kotlin.Int? = null,

    /* Count of vertical pixels presented. */
    @Json(name = "height")
    val height: kotlin.Int? = null,

    /* Whether or not this data stream carries HDR content. */
    @Json(name = "isHdr")
    val isHdr: kotlin.Boolean? = null

) {


}

