/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MediaBitrateInfoBitrate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bitrate 
 */


data class CdnDeliveryV3MediaBitrateInfo (

    @Json(name = "bitrate")
    val bitrate: CdnDeliveryV3MediaBitrateInfoBitrate? = null

) {


}

