/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.EdgeDataCenter

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An `origin`, if present, is a choice of base URL or server from which to load a `variant`'s content. If origin(s) exists in a group or variant, then one must be chosen in combination with the variant's `url`.
 *
 * @param url An absolute URL (possibly with trailing slash) which acts as the base of a delivery resource URI. This is always present.
 * @param queryUrl An absolute URL (possibly with trailing slash) which the client can use to query if the origin is active/working. This field may not be present. Perform an HTTP GET on this URL and expect an HTTP 200 in order to trust this origin.
 * @param datacenter 
 */


data class CdnDeliveryV3Origin (

    /* An absolute URL (possibly with trailing slash) which acts as the base of a delivery resource URI. This is always present. */
    @Json(name = "url")
    val url: java.net.URI,

    /* An absolute URL (possibly with trailing slash) which the client can use to query if the origin is active/working. This field may not be present. Perform an HTTP GET on this URL and expect an HTTP 200 in order to trust this origin. */
    @Json(name = "queryUrl")
    val queryUrl: java.net.URI? = null,

    @Json(name = "datacenter")
    val datacenter: EdgeDataCenter? = null

) {


}

