/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MetaAudio
import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MetaCommon
import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MetaImage
import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MetaLive
import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MetaVideo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Metadata information for this variant. Note that most/all child and grandchild properties are not required on purpose.
 *
 * @param common 
 * @param video 
 * @param audio 
 * @param image 
 * @param live 
 */


data class CdnDeliveryV3Meta (

    @Json(name = "common")
    val common: CdnDeliveryV3MetaCommon? = null,

    @Json(name = "video")
    val video: CdnDeliveryV3MetaVideo? = null,

    @Json(name = "audio")
    val audio: CdnDeliveryV3MetaAudio? = null,

    @Json(name = "image")
    val image: CdnDeliveryV3MetaImage? = null,

    @Json(name = "live")
    val live: CdnDeliveryV3MetaLive? = null

) {


}

