/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maximum Maximum bitrate observed for the data stream.
 * @param average Average bitrate observed for the data stream.
 */


data class CdnDeliveryV3MediaBitrateInfoBitrate (

    /* Maximum bitrate observed for the data stream. */
    @Json(name = "maximum")
    val maximum: java.math.BigDecimal? = null,

    /* Average bitrate observed for the data stream. */
    @Json(name = "average")
    val average: java.math.BigDecimal? = null

) {


}

