/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3MetaCommonAccess

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertySize Size of the corresponding media file, measured in bytes.
 * @param access 
 */


data class CdnDeliveryV3MetaCommon (

    /* Size of the corresponding media file, measured in bytes. */
    @Json(name = "size")
    val propertySize: java.math.BigDecimal? = null,

    @Json(name = "access")
    val access: CdnDeliveryV3MetaCommonAccess? = null

) {


}

