/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lowLatencyExtension - `llhls`: 🍎-backed low-latency HLS extension. - `clhls`: Community-backed low-latency HLS extension. - `ivshls`: IVS custom low-latency HLS extension. - `lldash`: DASH-IF-backed low-Latency DASH extension.
 */


data class CdnDeliveryV3MetaLive (

    /* - `llhls`: 🍎-backed low-latency HLS extension. - `clhls`: Community-backed low-latency HLS extension. - `ivshls`: IVS custom low-latency HLS extension. - `lldash`: DASH-IF-backed low-Latency DASH extension. */
    @Json(name = "lowLatencyExtension")
    val lowLatencyExtension: CdnDeliveryV3MetaLive.LowLatencyExtension? = null

) {

    /**
     * - `llhls`: 🍎-backed low-latency HLS extension. - `clhls`: Community-backed low-latency HLS extension. - `ivshls`: IVS custom low-latency HLS extension. - `lldash`: DASH-IF-backed low-Latency DASH extension.
     *
     * Values: llhls,clhls,ivshls,lldash
     */
    @JsonClass(generateAdapter = false)
    enum class LowLatencyExtension(val value: kotlin.String) {
        @Json(name = "llhls") llhls("llhls"),
        @Json(name = "clhls") clhls("clhls"),
        @Json(name = "ivshls") ivshls("ivshls"),
        @Json(name = "lldash") lldash("lldash");
    }

}

