/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param width Count of horizontal pixels presented.
 * @param height Count of vertical pixels presented.
 * @param isHdr Whether or not this data stream carries HDR content.
 */


data class CdnDeliveryV3ImagePresentationCharacteristics (

    /* Count of horizontal pixels presented. */
    @Json(name = "width")
    val width: kotlin.Int? = null,

    /* Count of vertical pixels presented. */
    @Json(name = "height")
    val height: kotlin.Int? = null,

    /* Whether or not this data stream carries HDR content. */
    @Json(name = "isHdr")
    val isHdr: kotlin.Boolean? = null

) {


}

