/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3Group

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param groups `groups` may consist of zero or more elements.
 */


data class CdnDeliveryV3Response (

    /* `groups` may consist of zero or more elements. */
    @Json(name = "groups")
    val groups: kotlin.collections.List<CdnDeliveryV3Group>

) {


}

