/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3Origin
import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3Variant

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A group is a logical grouping/separation of variants. At this time, there are no examples of more than one group in a response.
 *
 * @param variants `variants` may consist of zero or more elements.
 * @param origins If `origins` is present, it will consist of one or more elements.
 */


data class CdnDeliveryV3Group (

    /* `variants` may consist of zero or more elements. */
    @Json(name = "variants")
    val variants: kotlin.collections.List<CdnDeliveryV3Variant>,

    /* If `origins` is present, it will consist of one or more elements. */
    @Json(name = "origins")
    val origins: kotlin.collections.List<CdnDeliveryV3Origin>? = null

) {


}

