/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param codec RFC 6381 codec string indicating stream data chunk format.
 * @param codecSimple RFC 6381 codec string indicating stream format on the most basic level, without the addition of profile/level/etc. information.
 * @param mimeType MIME-type for individual stream data chunks (as opposed to a containing playlist).
 */


data class CdnDeliveryV3MediaIdentityCharacteristics (

    /* RFC 6381 codec string indicating stream data chunk format. */
    @Json(name = "codec")
    val codec: kotlin.String? = null,

    /* RFC 6381 codec string indicating stream format on the most basic level, without the addition of profile/level/etc. information. */
    @Json(name = "codecSimple")
    val codecSimple: kotlin.String? = null,

    /* MIME-type for individual stream data chunks (as opposed to a containing playlist). */
    @Json(name = "mimeType")
    val mimeType: kotlin.String? = null

) {


}

