/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV2ResourceModel
import com.coulterpeterson.floatnative.openapi.models.EdgeModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param edges 
 * @param client 
 * @param strategy Which download/streaming strategy to use. If `cdn`, then a `cdn` property will be included with the response. Otherwise, if set to `client`, then a `client` property will be included with the response. The cdn or client property should be combined with the `resource` property to perform the download/stream.
 * @param resource 
 */


data class CdnDeliveryV2DownloadResponse (

    @Json(name = "edges")
    val edges: kotlin.collections.List<EdgeModel>,

    @Json(name = "client")
    val client: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Which download/streaming strategy to use. If `cdn`, then a `cdn` property will be included with the response. Otherwise, if set to `client`, then a `client` property will be included with the response. The cdn or client property should be combined with the `resource` property to perform the download/stream. */
    @Json(name = "strategy")
    val strategy: CdnDeliveryV2DownloadResponse.Strategy,

    @Json(name = "resource")
    val resource: CdnDeliveryV2ResourceModel

) {

    /**
     * Which download/streaming strategy to use. If `cdn`, then a `cdn` property will be included with the response. Otherwise, if set to `client`, then a `client` property will be included with the response. The cdn or client property should be combined with the `resource` property to perform the download/stream.
     *
     * Values: cdn,client
     */
    @JsonClass(generateAdapter = false)
    enum class Strategy(val value: kotlin.String) {
        @Json(name = "cdn") cdn("cdn"),
        @Json(name = "client") client("client");
    }

}

