/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV2QualityLevelModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param qualityLevels 
 * @param qualityLevelParams For each `qualityLevel` above, there will be an entry in this map where the property name matches the `qulityLevel[].name` containing a token to apply to the URL.
 */


data class CdnDeliveryV2ResourceModelData (

    @Json(name = "qualityLevels")
    val qualityLevels: kotlin.collections.List<CdnDeliveryV2QualityLevelModel>? = null,

    /* For each `qualityLevel` above, there will be an entry in this map where the property name matches the `qulityLevel[].name` containing a token to apply to the URL. */
    @Json(name = "qualityLevelParams")
    val qualityLevelParams: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

