/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3Meta
import com.coulterpeterson.floatnative.openapi.models.CdnDeliveryV3Origin

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A `variant` represents one variant of a source of media. The most common differenitating factor between variants is video resolution, but there may be more variations based on `isHdr`, codecs, FPS, etc. It's possible that groups of variants may be divided into separate `groups` elements.
 *
 * @param name A programmatic name for this variant, for use with uniquely identifying this variant.
 * @param label A display-friendly label for this variant, for use in the UI.
 * @param url A relative *or* absolute URL containing resource information for this variant. Compared to the V2 API, this URL does not contain template information and will not need to be modified before use, other than optionally combining with an origin. This value may contain a trailing slash.  If this URL is absolute, it may be used as-is in order to load the media content. If this URL is relative, then it should be combined with an origin base URL. In order of preference: 1) use an origin from this variant object, 2) use an origin from this variant's group object, 3) use `https://floatplane.com`.  Do not use an origin from a different group, or from a different variant, as this may result in errors. 
 * @param origins If `origins` is present, it will consist of one or more elements.
 * @param order An optional field prescribing this variant's order in relation to other variants. No guarantees other than being greater than or less than the order of other variants within this group (e.g., order may not be consecutive).
 * @param enabled An optional field indicating if this variant is enabled. If this is not enabled, it may be visible to the user, but not selectable. If this field is not present, assume a default value of `false`, for safety.
 * @param hidden An optional field indicating if this variant should be hidden. If hidden, it should not be shown to the user nor considered in any code logic. If this field is not present, assume a default value of `false`. Only truthy values should hide a variant.
 * @param meta 
 * @param mimeType An optional string describing the MIME Type of this media source.
 */


data class CdnDeliveryV3Variant (

    /* A programmatic name for this variant, for use with uniquely identifying this variant. */
    @Json(name = "name")
    val name: kotlin.String,

    /* A display-friendly label for this variant, for use in the UI. */
    @Json(name = "label")
    val label: kotlin.String,

    /* A relative *or* absolute URL containing resource information for this variant. Compared to the V2 API, this URL does not contain template information and will not need to be modified before use, other than optionally combining with an origin. This value may contain a trailing slash.  If this URL is absolute, it may be used as-is in order to load the media content. If this URL is relative, then it should be combined with an origin base URL. In order of preference: 1) use an origin from this variant object, 2) use an origin from this variant's group object, 3) use `https://floatplane.com`.  Do not use an origin from a different group, or from a different variant, as this may result in errors.  */
    @Json(name = "url")
    val url: kotlin.String,

    /* If `origins` is present, it will consist of one or more elements. */
    @Json(name = "origins")
    val origins: kotlin.collections.List<CdnDeliveryV3Origin>? = null,

    /* An optional field prescribing this variant's order in relation to other variants. No guarantees other than being greater than or less than the order of other variants within this group (e.g., order may not be consecutive). */
    @Json(name = "order")
    val order: kotlin.Long? = null,

    /* An optional field indicating if this variant is enabled. If this is not enabled, it may be visible to the user, but not selectable. If this field is not present, assume a default value of `false`, for safety. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* An optional field indicating if this variant should be hidden. If hidden, it should not be shown to the user nor considered in any code logic. If this field is not present, assume a default value of `false`. Only truthy values should hide a variant. */
    @Json(name = "hidden")
    val hidden: kotlin.Boolean? = null,

    @Json(name = "meta")
    val meta: CdnDeliveryV3Meta? = null,

    /* An optional string describing the MIME Type of this media source. */
    @Json(name = "mimeType")
    val mimeType: kotlin.String? = null

) {


}

