/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deniedReason - `isMissingPermission`: Indicates that the requester is lacking a required plan or other form of permission entitling on to access the corresponding resource. - `isProcessing`: Indicates that the corresponding resource is processing. Clients may choose to periodically refetch an asset's info when it has reported this state. - `isBroken`: Indicates that the corresponding resource is defective in some manner which has rendered it currently inaccessible. It is possible that the asset will be repaired at some later point in time. Clients may choose to periodically refetch an asset's info when it has reported this state.
 * @param deniedMessage Message describing in human-readable terms why access has been witheld for a resource.
 */


data class CdnDeliveryV3MetaCommonAccess (

    /* - `isMissingPermission`: Indicates that the requester is lacking a required plan or other form of permission entitling on to access the corresponding resource. - `isProcessing`: Indicates that the corresponding resource is processing. Clients may choose to periodically refetch an asset's info when it has reported this state. - `isBroken`: Indicates that the corresponding resource is defective in some manner which has rendered it currently inaccessible. It is possible that the asset will be repaired at some later point in time. Clients may choose to periodically refetch an asset's info when it has reported this state. */
    @Json(name = "deniedReason")
    val deniedReason: CdnDeliveryV3MetaCommonAccess.DeniedReason? = null,

    /* Message describing in human-readable terms why access has been witheld for a resource. */
    @Json(name = "deniedMessage")
    val deniedMessage: kotlin.String? = null

) {

    /**
     * - `isMissingPermission`: Indicates that the requester is lacking a required plan or other form of permission entitling on to access the corresponding resource. - `isProcessing`: Indicates that the corresponding resource is processing. Clients may choose to periodically refetch an asset's info when it has reported this state. - `isBroken`: Indicates that the corresponding resource is defective in some manner which has rendered it currently inaccessible. It is possible that the asset will be repaired at some later point in time. Clients may choose to periodically refetch an asset's info when it has reported this state.
     *
     * Values: isMissingPermission,isProcessing,isBroken
     */
    @JsonClass(generateAdapter = false)
    enum class DeniedReason(val value: kotlin.String) {
        @Json(name = "isMissingPermission") isMissingPermission("isMissingPermission"),
        @Json(name = "isProcessing") isProcessing("isProcessing"),
        @Json(name = "isBroken") isBroken("isBroken");
    }

}

