/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ImageModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param urlname Shown in the browser URL.
 * @param about 
 * @param icon 
 * @param creator 
 * @param order 
 * @param cover 
 * @param card 
 * @param socialLinks 
 */


data class ChannelModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    /* Shown in the browser URL. */
    @Json(name = "urlname")
    val urlname: kotlin.String,

    @Json(name = "about")
    val about: kotlin.String,

    @Json(name = "icon")
    val icon: ImageModel,

    @Json(name = "creator")
    val creator: kotlin.String? = null,

    @Json(name = "order")
    val order: kotlin.Int? = null,

    @Json(name = "cover")
    val cover: ImageModel? = null,

    @Json(name = "card")
    val card: ImageModel? = null,

    @Json(name = "socialLinks")
    val socialLinks: kotlin.collections.Map<kotlin.String, java.net.URI>? = null

) {


}

