/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token The two-factor authentication token that the user inputs to complete the login process.
 */


data class CheckFor2faLoginRequest (

    /* The two-factor authentication token that the user inputs to complete the login process. */
    @Json(name = "token")
    val token: kotlin.String

) {


}

