/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param width 
 * @param height 
 * @param path 
 */


data class ChildImageModel (

    @Json(name = "width")
    val width: kotlin.Int,

    @Json(name = "height")
    val height: kotlin.Int,

    @Json(name = "path")
    val path: java.net.URI

) {


}

