/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creatorId 
 * @param skip 
 * @param limit 
 * @param activeOnly 
 */


data class CmsListPollsRequest (

    @Json(name = "creatorId")
    val creatorId: kotlin.String,

    @Json(name = "skip")
    val skip: kotlin.Int,

    @Json(name = "limit")
    val limit: kotlin.Int,

    @Json(name = "activeOnly")
    val activeOnly: kotlin.Boolean

) {


}

