/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment The GUID of the comment being liked.
 * @param blogPost The GUID of the post the comment is on.
 */


data class CommentLikeV3PostRequest (

    /* The GUID of the comment being liked. */
    @Json(name = "comment")
    val comment: kotlin.String,

    /* The GUID of the post the comment is on. */
    @Json(name = "blogPost")
    val blogPost: kotlin.String

) {


}

