/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blogPost The GUID of the blogPost the comment should be posted to.
 * @param text The text of the comment being posted.
 */


data class CommentV3PostRequest (

    /* The GUID of the blogPost the comment should be posted to. */
    @Json(name = "blogPost")
    val blogPost: kotlin.String,

    /* The text of the comment being posted. */
    @Json(name = "text")
    val text: kotlin.String

) {


}

