/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CommentV3PostResponseInteractionCounts
import com.coulterpeterson.floatnative.openapi.models.UserModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param blogPost 
 * @param user 
 * @param text 
 * @param replying 
 * @param postDate 
 * @param editDate 
 * @param editCount 
 * @param isEdited 
 * @param likes 
 * @param dislikes 
 * @param score 
 * @param interactionCounts 
 * @param userInteraction 
 * @param pinDate 
 * @param totalReplies 
 * @param replies This is present (but possibly empty) for top-level comments. This is never present for reply comments.
 */


data class CommentModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "blogPost")
    val blogPost: kotlin.String,

    @Json(name = "user")
    val user: UserModel,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "replying")
    val replying: kotlin.String?,

    @Json(name = "postDate")
    val postDate: java.time.OffsetDateTime,

    @Json(name = "editDate")
    val editDate: java.time.OffsetDateTime?,

    @Json(name = "editCount")
    val editCount: kotlin.Int,

    @Json(name = "isEdited")
    val isEdited: kotlin.Boolean,

    @Json(name = "likes")
    val likes: kotlin.Int,

    @Json(name = "dislikes")
    val dislikes: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "interactionCounts")
    val interactionCounts: CommentV3PostResponseInteractionCounts,

    @Json(name = "userInteraction")
    val userInteraction: kotlin.collections.List<CommentModel.UserInteraction>?,

    @Json(name = "pinDate")
    val pinDate: java.time.OffsetDateTime? = null,

    @Json(name = "totalReplies")
    val totalReplies: kotlin.Int? = null,

    /* This is present (but possibly empty) for top-level comments. This is never present for reply comments. */
    @Json(name = "replies")
    val replies: kotlin.collections.List<CommentModel>? = null

) {

    /**
     * 
     *
     * Values: like,dislike
     */
    @JsonClass(generateAdapter = false)
    enum class UserInteraction(val value: kotlin.String) {
        @Json(name = "like") like("like"),
        @Json(name = "dislike") dislike("dislike");
    }

}

