/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CommentV3PostResponseInteractionCounts
import com.coulterpeterson.floatnative.openapi.models.UserModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param blogPost 
 * @param user 
 * @param text 
 * @param replying 
 * @param postDate 
 * @param editDate 
 * @param editCount 
 * @param isEdited 
 * @param likes 
 * @param dislikes 
 * @param score 
 * @param interactionCounts 
 */


data class CommentV3PostResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "blogPost")
    val blogPost: kotlin.String,

    @Json(name = "user")
    val user: UserModel,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "replying")
    val replying: kotlin.String,

    @Json(name = "postDate")
    val postDate: kotlin.String,

    @Json(name = "editDate")
    val editDate: kotlin.String,

    @Json(name = "editCount")
    val editCount: kotlin.Int,

    @Json(name = "isEdited")
    val isEdited: kotlin.Boolean,

    @Json(name = "likes")
    val likes: kotlin.Int,

    @Json(name = "dislikes")
    val dislikes: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "interactionCounts")
    val interactionCounts: CommentV3PostResponseInteractionCounts

) {


}

