/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param like 
 * @param dislike 
 */


data class CommentV3PostResponseInteractionCounts (

    @Json(name = "like")
    val like: kotlin.Int,

    @Json(name = "dislike")
    val dislike: kotlin.Int

) {


}

