/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ConnectedAccountModelConnectedAccountData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param remoteUserId 
 * @param remoteUserName 
 * @param `data` 
 */


data class ConnectedAccountModelConnectedAccount (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "remoteUserId")
    val remoteUserId: kotlin.String,

    @Json(name = "remoteUserName")
    val remoteUserName: kotlin.String,

    @Json(name = "data")
    val `data`: ConnectedAccountModelConnectedAccountData?

) {


}

