/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ConnectedAccountModelConnectedAccount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key Unique identifier for the account type.
 * @param name Display-friendly label for the `key`.
 * @param enabled Determines if the system allows this account to be connected to.
 * @param iconWhite 
 * @param connectedAccount 
 * @param connected If true, the user is connected and the `connectedAccount` will have data about the account.
 * @param isAccountProvider 
 */


data class ConnectedAccountModel (

    /* Unique identifier for the account type. */
    @Json(name = "key")
    val key: kotlin.String,

    /* Display-friendly label for the `key`. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Determines if the system allows this account to be connected to. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "iconWhite")
    val iconWhite: kotlin.String,

    @Json(name = "connectedAccount")
    val connectedAccount: ConnectedAccountModelConnectedAccount?,

    /* If true, the user is connected and the `connectedAccount` will have data about the account. */
    @Json(name = "connected")
    val connected: kotlin.Boolean,

    @Json(name = "isAccountProvider")
    val isAccountProvider: kotlin.Boolean

) {


}

