/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.BlogPostModelV3
import com.coulterpeterson.floatnative.openapi.models.ContentCreatorListLastItems

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blogPosts 
 * @param lastElements Information about paging: what the last ID retrieve is and if more posts can be retrieved afterward for subsequent requests.
 */


data class ContentCreatorListV3Response (

    @Json(name = "blogPosts")
    val blogPosts: kotlin.collections.List<BlogPostModelV3>,

    /* Information about paging: what the last ID retrieve is and if more posts can be retrieved afterward for subsequent requests. */
    @Json(name = "lastElements")
    val lastElements: kotlin.collections.List<ContentCreatorListLastItems>

) {


}

