/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creatorId 
 * @param blogPostId This may be returned as `null` if no blog posts for this creator appeared yet on this page of blog posts. However, Floatplane will complain if this is sent with a `null` value.
 * @param moreFetchable 
 */


data class ContentCreatorListLastItems (

    @Json(name = "creatorId")
    val creatorId: kotlin.String,

    /* This may be returned as `null` if no blog posts for this creator appeared yet on this page of blog posts. However, Floatplane will complain if this is sent with a `null` value. */
    @Json(name = "blogPostId")
    val blogPostId: kotlin.String?,

    @Json(name = "moreFetchable")
    val moreFetchable: kotlin.Boolean

) {


}

