/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentType 
 * @param id 
 */


data class ContentLikeV3Request (

    @Json(name = "contentType")
    val contentType: ContentLikeV3Request.ContentType,

    @Json(name = "id")
    val id: kotlin.String

) {

    /**
     * 
     *
     * Values: blogPost
     */
    @JsonClass(generateAdapter = false)
    enum class ContentType(val value: kotlin.String) {
        @Json(name = "blogPost") blogPost("blogPost");
    }

}

