/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Text track identifier.
 * @param src URL to a text track file, usually .vtt files.
 * @param kind Usually 'caption'.
 * @param language Language code, e.g. 'en'.
 * @param generated Whether the text track has been generated.
 * @param processing Whether the text track is processing.
 */


data class ContentVideoV3ResponseTextTracksInner (

    /* Text track identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    /* URL to a text track file, usually .vtt files. */
    @Json(name = "src")
    val src: kotlin.String,

    /* Usually 'caption'. */
    @Json(name = "kind")
    val kind: kotlin.String,

    /* Language code, e.g. 'en'. */
    @Json(name = "language")
    val language: kotlin.String,

    /* Whether the text track has been generated. */
    @Json(name = "generated")
    val generated: kotlin.Boolean,

    /* Whether the text track is processing. */
    @Json(name = "processing")
    val processing: kotlin.Boolean

) {


}

