/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ContentVideoV3ResponseLevelsInner
import com.coulterpeterson.floatnative.openapi.models.ContentVideoV3ResponseTextTracksInner
import com.coulterpeterson.floatnative.openapi.models.ImageModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param guid 
 * @param title 
 * @param type 
 * @param description 
 * @param releaseDate 
 * @param duration Unit: seconds.
 * @param creator 
 * @param likes 
 * @param dislikes 
 * @param score 
 * @param isProcessing 
 * @param primaryBlogPost 
 * @param thumbnail 
 * @param isAccessible If false, the post should be marked as locked and not viewable by the user.
 * @param blogPosts 
 * @param timelineSprite 
 * @param userInteraction 
 * @param levels 
 * @param progress The watch progress of the video, in seconds. If no progress has yet been posted to the video, then this field may not appear.
 * @param textTracks 
 */


data class ContentVideoV3Response (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "guid")
    val guid: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "releaseDate")
    val releaseDate: java.time.OffsetDateTime?,

    /* Unit: seconds. */
    @Json(name = "duration")
    val duration: java.math.BigDecimal,

    @Json(name = "creator")
    val creator: kotlin.String,

    @Json(name = "likes")
    val likes: kotlin.Int,

    @Json(name = "dislikes")
    val dislikes: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "isProcessing")
    val isProcessing: kotlin.Boolean,

    @Json(name = "primaryBlogPost")
    val primaryBlogPost: kotlin.String,

    @Json(name = "thumbnail")
    val thumbnail: ImageModel,

    /* If false, the post should be marked as locked and not viewable by the user. */
    @Json(name = "isAccessible")
    val isAccessible: kotlin.Boolean,

    @Json(name = "blogPosts")
    val blogPosts: kotlin.collections.List<kotlin.String>,

    @Json(name = "timelineSprite")
    val timelineSprite: ImageModel,

    @Json(name = "userInteraction")
    val userInteraction: kotlin.collections.List<ContentVideoV3Response.UserInteraction>?,

    @Json(name = "levels")
    val levels: kotlin.collections.List<ContentVideoV3ResponseLevelsInner>,

    /* The watch progress of the video, in seconds. If no progress has yet been posted to the video, then this field may not appear. */
    @Json(name = "progress")
    val progress: kotlin.Int? = null,

    @Json(name = "textTracks")
    val textTracks: kotlin.collections.List<ContentVideoV3ResponseTextTracksInner>? = null

) {

    /**
     * 
     *
     * Values: like,dislike
     */
    @JsonClass(generateAdapter = false)
    enum class UserInteraction(val value: kotlin.String) {
        @Json(name = "like") like("like"),
        @Json(name = "dislike") dislike("dislike");
    }

}

