/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param width 
 * @param height 
 * @param label 
 * @param order 
 */


data class ContentVideoV3ResponseLevelsInner (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "width")
    val width: kotlin.Int,

    @Json(name = "height")
    val height: kotlin.Int,

    @Json(name = "label")
    val label: kotlin.String,

    @Json(name = "order")
    val order: kotlin.Int

) {


}

