/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creatorId 
 * @param type 
 * @param title 
 * @param options 
 * @param duration 
 */


data class CreateLivePollRequest (

    @Json(name = "creatorId")
    val creatorId: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "options")
    val options: kotlin.collections.List<kotlin.String>,

    @Json(name = "duration")
    val duration: kotlin.String

) {


}

