/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.DiscordServerModel
import com.coulterpeterson.floatnative.openapi.models.ImageModel
import com.coulterpeterson.floatnative.openapi.models.LiveStreamModel
import com.coulterpeterson.floatnative.openapi.models.SubscriptionPlanModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param owner 
 * @param title 
 * @param urlname Shown in the browser URL, and used in `/creator/named` queries.
 * @param description 
 * @param about 
 * @param category 
 * @param cover 
 * @param icon 
 * @param liveStream 
 * @param subscriptionPlans 
 * @param discoverable 
 * @param subscriberCountDisplay 
 * @param incomeDisplay 
 * @param socialLinks 
 * @param discordServers 
 * @param defaultChannel 
 */


data class CreatorModelV2Extended (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "owner")
    val owner: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    /* Shown in the browser URL, and used in `/creator/named` queries. */
    @Json(name = "urlname")
    val urlname: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "about")
    val about: kotlin.String,

    @Json(name = "category")
    val category: kotlin.String,

    @Json(name = "cover")
    val cover: ImageModel?,

    @Json(name = "icon")
    val icon: ImageModel,

    @Json(name = "liveStream")
    val liveStream: LiveStreamModel?,

    @Json(name = "subscriptionPlans")
    val subscriptionPlans: kotlin.collections.List<SubscriptionPlanModel>?,

    @Json(name = "discoverable")
    val discoverable: kotlin.Boolean,

    @Json(name = "subscriberCountDisplay")
    val subscriberCountDisplay: kotlin.String,

    @Json(name = "incomeDisplay")
    val incomeDisplay: kotlin.Boolean,

    @Json(name = "socialLinks")
    val socialLinks: kotlin.collections.Map<kotlin.String, java.net.URI>,

    @Json(name = "discordServers")
    val discordServers: kotlin.collections.List<DiscordServerModel>,

    @Json(name = "defaultChannel")
    val defaultChannel: kotlin.String? = null

) {


}

