/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param guildName 
 * @param guildIcon 
 * @param inviteLink 
 * @param inviteMode 
 */


data class DiscordServerModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "guildName")
    val guildName: kotlin.String,

    @Json(name = "guildIcon")
    val guildIcon: kotlin.String,

    @Json(name = "inviteLink")
    val inviteLink: java.net.URI?,

    @Json(name = "inviteMode")
    val inviteMode: kotlin.String

) {


}

