/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Location information for a datacenter. Not required.
 *
 * @param countryCode 
 * @param regionCode 
 * @param latitude 
 * @param longitude 
 */


data class EdgeDataCenter (

    @Json(name = "countryCode")
    val countryCode: kotlin.String,

    @Json(name = "regionCode")
    val regionCode: kotlin.String,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal

) {


}

