/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.EdgeDataCenter

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hostname 
 * @param queryPort 
 * @param bandwidth 
 * @param allowDownload 
 * @param allowStreaming 
 * @param datacenter 
 */


data class EdgeModel (

    @Json(name = "hostname")
    val hostname: kotlin.String,

    @Json(name = "queryPort")
    val queryPort: kotlin.Int,

    @Json(name = "bandwidth")
    val bandwidth: kotlin.Long,

    @Json(name = "allowDownload")
    val allowDownload: kotlin.Boolean,

    @Json(name = "allowStreaming")
    val allowStreaming: kotlin.Boolean,

    @Json(name = "datacenter")
    val datacenter: EdgeDataCenter

) {


}

