/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.EdgeModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param edges 
 * @param client 
 */


data class EdgesModel (

    @Json(name = "edges")
    val edges: kotlin.collections.List<EdgeModel>,

    @Json(name = "client")
    val client: kotlin.collections.Map<kotlin.String, kotlin.Any>

) {


}

