/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ErrorModelErrorsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param errors 
 * @param message May be undefined.
 */


data class ErrorModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "errors")
    val errors: kotlin.collections.List<ErrorModelErrorsInner>,

    /* May be undefined. */
    @Json(name = "message")
    val message: kotlin.String? = null

) {


}

