/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param message May be undefined.
 * @param `data` May be undefined.
 */


data class ErrorModelErrorsInner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    /* May be undefined. */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* May be undefined. */
    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

