/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param updatedAt 
 * @param id 
 * @param question 
 * @param answer This field may contain HTML that should be rendered.
 * @param status 
 * @param link 
 * @param order 
 * @param faqSection 
 */


data class FaqSectionModelFaqsInner (

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime?,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "question")
    val question: kotlin.String,

    /* This field may contain HTML that should be rendered. */
    @Json(name = "answer")
    val answer: kotlin.String,

    @Json(name = "status")
    val status: FaqSectionModelFaqsInner.Status,

    @Json(name = "link")
    val link: kotlin.String,

    @Json(name = "order")
    val order: java.math.BigDecimal,

    @Json(name = "faqSection")
    val faqSection: kotlin.String

) {

    /**
     * 
     *
     * Values: `public`
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "public") `public`("public");
    }

}

