/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.FaqSectionModelFaqsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param faqs 
 * @param createdAt 
 * @param updatedAt 
 * @param id 
 * @param name 
 * @param description 
 * @param status 
 * @param order 
 */


data class FaqSectionModel (

    @Json(name = "faqs")
    val faqs: kotlin.collections.List<FaqSectionModelFaqsInner>,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime?,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "status")
    val status: FaqSectionModel.Status,

    @Json(name = "order")
    val order: java.math.BigDecimal

) {

    /**
     * 
     *
     * Values: `public`
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "public") `public`("public");
    }

}

