/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.GetCaptchaInfoResponseV2VariantsAndroid

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invisible 
 */


data class GetCaptchaInfoResponseV3Variants (

    @Json(name = "invisible")
    val invisible: GetCaptchaInfoResponseV2VariantsAndroid

) {


}

