/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.GetCaptchaInfoResponseV2
import com.coulterpeterson.floatnative.openapi.models.GetCaptchaInfoResponseV3

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param v2 
 * @param v3 
 */


data class GetCaptchaInfoResponse (

    @Json(name = "v2")
    val v2: GetCaptchaInfoResponseV2,

    @Json(name = "v3")
    val v3: GetCaptchaInfoResponseV3

) {


}

