/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ids The identifiers of the blog posts from which progress should be retrieved.
 * @param contentType The type of the corresponding identifiers. The only value currently is `blogPost`.
 */


data class GetProgressRequest (

    /* The identifiers of the blog posts from which progress should be retrieved. */
    @Json(name = "ids")
    val ids: kotlin.collections.List<kotlin.String>,

    /* The type of the corresponding identifiers. The only value currently is `blogPost`. */
    @Json(name = "contentType")
    val contentType: GetProgressRequest.ContentType

) {

    /**
     * The type of the corresponding identifiers. The only value currently is `blogPost`.
     *
     * Values: blogPost
     */
    @JsonClass(generateAdapter = false)
    enum class ContentType(val value: kotlin.String) {
        @Json(name = "blogPost") blogPost("blogPost");
    }

}

