/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param progress Percentage of the blog post's media that has been consumed so far. Ranges from 0 to 100.
 */


data class GetProgressResponseInner (

    @Json(name = "id")
    val id: kotlin.String,

    /* Percentage of the blog post's media that has been consumed so far. Ranges from 0 to 100. */
    @Json(name = "progress")
    val progress: kotlin.Int

) {


}

