/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ImageModel
import com.coulterpeterson.floatnative.openapi.models.LiveStreamModelOffline

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param thumbnail 
 * @param owner 
 * @param streamPath 
 * @param offline 
 * @param channel The creator channel this livestream belongs to.
 */


data class LiveStreamModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "thumbnail")
    val thumbnail: ImageModel?,

    @Json(name = "owner")
    val owner: kotlin.String,

    @Json(name = "streamPath")
    val streamPath: kotlin.String,

    @Json(name = "offline")
    val offline: LiveStreamModelOffline,

    /* The creator channel this livestream belongs to. */
    @Json(name = "channel")
    val channel: kotlin.String? = null

) {


}

