/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ImageModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param description 
 * @param thumbnail 
 */


data class LiveStreamModelOffline (

    @Json(name = "title")
    val title: kotlin.String?,

    @Json(name = "description")
    val description: kotlin.String?,

    @Json(name = "thumbnail")
    val thumbnail: ImageModel?

) {


}

