/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInnerPlanCreator

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param creator 
 */


data class PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInnerPlan (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "creator")
    val creator: PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInnerPlanCreator

) {


}

