/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param brand 
 * @param last4 
 * @param expMonth 
 * @param expYear 
 * @param name 
 */


data class PaymentMethodModelCard (

    @Json(name = "brand")
    val brand: kotlin.String,

    @Json(name = "last4")
    val last4: kotlin.String,

    @Json(name = "exp_month")
    val expMonth: kotlin.Int,

    @Json(name = "exp_year")
    val expYear: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String

) {


}

