/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.PaymentInvoiceListV2ResponseInvoicesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invoices 
 */


data class PaymentInvoiceListV2Response (

    @Json(name = "invoices")
    val invoices: kotlin.collections.List<PaymentInvoiceListV2ResponseInvoicesInner>

) {


}

