/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param amountDue 
 * @param amountTax 
 * @param attemptCount 
 * @param currency 
 * @param date 
 * @param dateDue 
 * @param periodStart 
 * @param periodEnd 
 * @param nextPaymentAttempt 
 * @param paid 
 * @param forgiven 
 * @param refunded 
 * @param subscriptions The subscriptions this invoice is in reference to.
 */


data class PaymentInvoiceListV2ResponseInvoicesInner (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "amountDue")
    val amountDue: java.math.BigDecimal,

    @Json(name = "amountTax")
    val amountTax: java.math.BigDecimal,

    @Json(name = "attemptCount")
    val attemptCount: kotlin.Int,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "date")
    val date: java.time.OffsetDateTime,

    @Json(name = "dateDue")
    val dateDue: java.time.OffsetDateTime?,

    @Json(name = "periodStart")
    val periodStart: java.time.OffsetDateTime,

    @Json(name = "periodEnd")
    val periodEnd: java.time.OffsetDateTime,

    @Json(name = "nextPaymentAttempt")
    val nextPaymentAttempt: java.time.OffsetDateTime?,

    @Json(name = "paid")
    val paid: kotlin.Boolean,

    @Json(name = "forgiven")
    val forgiven: kotlin.Boolean,

    @Json(name = "refunded")
    val refunded: kotlin.Boolean,

    /* The subscriptions this invoice is in reference to. */
    @Json(name = "subscriptions")
    val subscriptions: kotlin.collections.List<PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInner>?

) {


}

