/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInnerPlan

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param subscription 
 * @param periodStart 
 * @param periodEnd 
 * @param `value` 
 * @param amountSubtotal 
 * @param amountTotal 
 * @param amountTax 
 * @param plan 
 */


data class PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInner (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "subscription")
    val subscription: java.math.BigDecimal,

    @Json(name = "periodStart")
    val periodStart: java.time.OffsetDateTime?,

    @Json(name = "periodEnd")
    val periodEnd: java.time.OffsetDateTime?,

    @Json(name = "value")
    val `value`: java.math.BigDecimal,

    @Json(name = "amountSubtotal")
    val amountSubtotal: java.math.BigDecimal,

    @Json(name = "amountTotal")
    val amountTotal: java.math.BigDecimal,

    @Json(name = "amountTax")
    val amountTax: java.math.BigDecimal,

    @Json(name = "plan")
    val plan: PaymentInvoiceListV2ResponseInvoicesInnerSubscriptionsInnerPlan

) {


}

