/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.PaymentMethodModelCard

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param paymentProcessor 
 * @param default 
 * @param card 
 */


data class PaymentMethodModel (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "payment_processor")
    val paymentProcessor: kotlin.Int,

    @Json(name = "default")
    val default: kotlin.Boolean,

    @Json(name = "card")
    val card: PaymentMethodModelCard

) {


}

