/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param customerName 
 * @param postalCode 
 * @param line1 
 * @param city 
 * @param region 
 * @param country 
 * @param default 
 */


data class PaymentAddressModel (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "customerName")
    val customerName: kotlin.String,

    @Json(name = "postalCode")
    val postalCode: kotlin.String,

    @Json(name = "line1")
    val line1: kotlin.String,

    @Json(name = "city")
    val city: kotlin.String,

    @Json(name = "region")
    val region: kotlin.String,

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "default")
    val default: kotlin.Boolean

) {


}

