/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ImageModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param guid 
 * @param title 
 * @param type 
 * @param description 
 * @param likes 
 * @param dislikes 
 * @param score 
 * @param isProcessing 
 * @param creator 
 * @param primaryBlogPost 
 * @param thumbnail 
 * @param isAccessible If false, the post should be marked as locked and not viewable by the user.
 */


data class PictureAttachmentModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "guid")
    val guid: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "likes")
    val likes: kotlin.Int,

    @Json(name = "dislikes")
    val dislikes: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "isProcessing")
    val isProcessing: kotlin.Boolean,

    @Json(name = "creator")
    val creator: kotlin.String,

    @Json(name = "primaryBlogPost")
    val primaryBlogPost: kotlin.String,

    @Json(name = "thumbnail")
    val thumbnail: ImageModel,

    /* If false, the post should be marked as locked and not viewable by the user. */
    @Json(name = "isAccessible")
    val isAccessible: kotlin.Boolean

) {


}

