/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.PlanInfoV2ResponsePlansInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalSubscriberCount The total number of subscribers for this creator.
 * @param totalIncome The total amount of monthly income for this creator. This field tends to always be $0 for regular users.
 * @param plans 
 */


data class PlanInfoV2Response (

    /* The total number of subscribers for this creator. */
    @Json(name = "totalSubscriberCount")
    val totalSubscriberCount: kotlin.Int?,

    /* The total amount of monthly income for this creator. This field tends to always be $0 for regular users. */
    @Json(name = "totalIncome")
    val totalIncome: java.math.BigDecimal?,

    @Json(name = "plans")
    val plans: kotlin.collections.List<PlanInfoV2ResponsePlansInner>

) {


}

