/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.DiscordRoleModel
import com.coulterpeterson.floatnative.openapi.models.DiscordServerModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param price 
 * @param currency 
 * @param logo 
 * @param interval 
 * @param featured 
 * @param discordServers 
 * @param discordRoles 
 * @param createdAt 
 * @param updatedAt 
 * @param enabled 
 * @param paymentID 
 * @param trialPeriod 
 * @param creator 
 * @param userIsSubscribed 
 * @param enabledGlobal 
 * @param priceYearly 
 * @param allowGrandfatheredAccess 
 * @param userIsGrandfathered 
 */


data class PlanInfoV2ResponsePlansInner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "price")
    val price: kotlin.String?,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "logo")
    val logo: kotlin.String?,

    @Json(name = "interval")
    val interval: kotlin.String,

    @Json(name = "featured")
    val featured: kotlin.Boolean,

    @Json(name = "discordServers")
    val discordServers: kotlin.collections.List<DiscordServerModel>,

    @Json(name = "discordRoles")
    val discordRoles: kotlin.collections.List<DiscordRoleModel>,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime?,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "paymentID")
    val paymentID: kotlin.Int?,

    @Json(name = "trialPeriod")
    val trialPeriod: java.math.BigDecimal,

    @Json(name = "creator")
    val creator: kotlin.String,

    @Json(name = "userIsSubscribed")
    val userIsSubscribed: kotlin.Boolean,

    @Json(name = "enabledGlobal")
    val enabledGlobal: kotlin.Boolean,

    @Json(name = "priceYearly")
    val priceYearly: kotlin.String? = null,

    @Json(name = "allowGrandfatheredAccess")
    val allowGrandfatheredAccess: kotlin.Boolean? = null,

    @Json(name = "userIsGrandfathered")
    val userIsGrandfathered: kotlin.Boolean? = null

) {


}

