/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The video or audio attachment identifier for the piece of media that is being updated. Note: this is *not* the blogPost identifier.
 * @param contentType Which type of media the corresponding identifier is.
 * @param progress The progress through the media that has been consumed by the user, in seconds.
 */


data class UpdateProgressRequest (

    /* The video or audio attachment identifier for the piece of media that is being updated. Note: this is *not* the blogPost identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Which type of media the corresponding identifier is. */
    @Json(name = "contentType")
    val contentType: UpdateProgressRequest.ContentType,

    /* The progress through the media that has been consumed by the user, in seconds. */
    @Json(name = "progress")
    val progress: kotlin.Int

) {

    /**
     * Which type of media the corresponding identifier is.
     *
     * Values: video,audio
     */
    @JsonClass(generateAdapter = false)
    enum class ContentType(val value: kotlin.String) {
        @Json(name = "video") video("video"),
        @Json(name = "audio") audio("audio");
    }

}

