/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.UserInfoV2ResponseUsersInnerUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param user 
 */


data class UserInfoV2ResponseUsersInner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "user")
    val user: UserInfoV2ResponseUsersInnerUser

) {


}

