/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param twofactorEnabled 
 * @param twofactorBackupCodeEnabled 
 */


data class UserSecurityV2Response (

    @Json(name = "twofactorEnabled")
    val twofactorEnabled: kotlin.Boolean,

    @Json(name = "twofactorBackupCodeEnabled")
    val twofactorBackupCodeEnabled: kotlin.Boolean

) {


}

