/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ImageModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents some basic information of a user (id, username, and profile image).
 *
 * @param id 
 * @param username 
 * @param profileImage 
 */


data class UserModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "profileImage")
    val profileImage: ImageModel

) {


}

