/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ImageModel
import com.coulterpeterson.floatnative.openapi.models.UserModel
import com.coulterpeterson.floatnative.openapi.models.UserSelfModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param username 
 * @param profileImage 
 * @param email 
 * @param displayName 
 */


data class UserInfoV2ResponseUsersInnerUser (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "profileImage")
    val profileImage: ImageModel,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "displayName")
    val displayName: kotlin.String

) {


}

