/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The code name of this link type.
 * @param displayName The display-friendly name of this link type.
 * @param hostName The hostname that should be a part of the URL.
 */


data class UserLinksV3ResponseValueType (

    /* The code name of this link type. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The display-friendly name of this link type. */
    @Json(name = "displayName")
    val displayName: kotlin.String,

    /* The hostname that should be a part of the URL. */
    @Json(name = "hostName")
    val hostName: kotlin.String

) {


}

