/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.SubscriptionPlanModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startDate 
 * @param endDate 
 * @param paymentID 
 * @param interval 
 * @param plan 
 * @param creator 
 * @param paymentCancelled 
 */


data class UserSubscriptionModel (

    @Json(name = "startDate")
    val startDate: java.time.OffsetDateTime?,

    @Json(name = "endDate")
    val endDate: java.time.OffsetDateTime?,

    @Json(name = "paymentID")
    val paymentID: kotlin.Int?,

    @Json(name = "interval")
    val interval: kotlin.String,

    @Json(name = "plan")
    val plan: SubscriptionPlanModel,

    @Json(name = "creator")
    val creator: kotlin.String,

    @Json(name = "paymentCancelled")
    val paymentCancelled: kotlin.Boolean? = null

) {


}

