/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentEmail 
 * @param contentFirebase 
 * @param creatorMessageEmail 
 * @param user 
 * @param creator 
 * @param createdAt 
 * @param updatedAt 
 * @param id 
 */


data class UserNotificationModelUserNotificationSetting (

    @Json(name = "contentEmail")
    val contentEmail: kotlin.Boolean,

    @Json(name = "contentFirebase")
    val contentFirebase: kotlin.Boolean,

    @Json(name = "creatorMessageEmail")
    val creatorMessageEmail: kotlin.Boolean,

    @Json(name = "user")
    val user: kotlin.String,

    @Json(name = "creator")
    val creator: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

