/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.CreatorModelV2
import com.coulterpeterson.floatnative.openapi.models.UserNotificationModelUserNotificationSetting

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creator 
 * @param userNotificationSetting 
 */


data class UserNotificationModel (

    @Json(name = "creator")
    val creator: CreatorModelV2,

    @Json(name = "userNotificationSetting")
    val userNotificationSetting: UserNotificationModelUserNotificationSetting

) {


}

