/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param time 
 * @param comment 
 * @param postTitle 
 * @param postId 
 * @param creatorTitle 
 * @param creatorUrl 
 */


data class UserActivityV3ResponseActivityInner (

    @Json(name = "time")
    val time: java.time.OffsetDateTime,

    @Json(name = "comment")
    val comment: kotlin.String,

    @Json(name = "postTitle")
    val postTitle: kotlin.String,

    @Json(name = "postId")
    val postId: kotlin.String,

    @Json(name = "creatorTitle")
    val creatorTitle: kotlin.String,

    @Json(name = "creatorUrl")
    val creatorUrl: kotlin.String

) {


}

