/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.UserSelfV3Response

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param selfUser 
 */


data class UserStatusV3Response (

    @Json(name = "selfUser")
    val selfUser: UserSelfV3Response? = null

) {


}

