/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.UserInfoV2ResponseUsersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param users 
 */


data class UserInfoV2Response (

    @Json(name = "users")
    val users: kotlin.collections.List<UserInfoV2ResponseUsersInner>

) {


}

