/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.UserActivityV3ResponseActivityInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param activity 
 * @param visibility 
 */


data class UserActivityV3Response (

    @Json(name = "activity")
    val activity: kotlin.collections.List<UserActivityV3ResponseActivityInner>,

    @Json(name = "visibility")
    val visibility: kotlin.String

) {


}

