/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.UserLinksV3ResponseValueType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url The URL the user has configured for this link.
 * @param type 
 */


data class UserLinksV3ResponseValue (

    /* The URL the user has configured for this link. */
    @Json(name = "url")
    val url: java.net.URI,

    @Json(name = "type")
    val type: UserLinksV3ResponseValueType

) {


}

