/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creator 
 * @param `property` Use `contentEmail` for email notifications, and `contentFirebase` for push notifications.
 * @param newValue 
 */


data class UserNotificationUpdateV3PostRequest (

    @Json(name = "creator")
    val creator: kotlin.String,

    /* Use `contentEmail` for email notifications, and `contentFirebase` for push notifications. */
    @Json(name = "property")
    val `property`: UserNotificationUpdateV3PostRequest.`Property`,

    @Json(name = "newValue")
    val newValue: kotlin.Boolean

) {

    /**
     * Use `contentEmail` for email notifications, and `contentFirebase` for push notifications.
     *
     * Values: contentEmail,contentFirebase
     */
    @JsonClass(generateAdapter = false)
    enum class `Property`(val value: kotlin.String) {
        @Json(name = "contentEmail") contentEmail("contentEmail"),
        @Json(name = "contentFirebase") contentFirebase("contentFirebase");
    }

}

