/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pollId The id of the poll to vote on.
 * @param optionIndex The index of the options of the poll for which to vote. This should not be outside the bounds of the poll options.
 */


data class VotePollRequest (

    /* The id of the poll to vote on. */
    @Json(name = "pollId")
    val pollId: kotlin.String,

    /* The index of the options of the poll for which to vote. This should not be outside the bounds of the poll options. */
    @Json(name = "optionIndex")
    val optionIndex: kotlin.Int

) {


}

